package jana.util.jar;

import java.io.IOException;

public class OverwritingFileException extends IOException
{
	/**
	 * Generated by Eclipse
	 */
	private static final long serialVersionUID = 4437497175933118302L;

	public OverwritingFileException()
	{
		super();
	}

	public OverwritingFileException(String message, Throwable cause)
	{
		super(message, cause);
	}

	public OverwritingFileException(String message)
	{
		super(message);
	}

	public OverwritingFileException(Throwable cause)
	{
		super(cause);
	}
}
