(project
 (project-name "java")
 (java-version "This is a Dummy Project! -- Please Run analyze-system-libraries.sh")
 (project-directory "project-java")
 (project-library-directory "project-java/lib")
 (project-analysis-directory "project-java/lsp")
 (project-compilation-directory "project-java/bin")
 (project-transformation-directory "project-java/trn")
 (project-jar-file "")
 (project-final-jar-file "")
 (project-classname-dictionary-file "project-java/java.cnd")
 (project-debug-information-file "project-java/trn/java.dbg")
 (project-library-jar-files)
 (project-analysis-filename-extensions ((uncompressed "lisp") (compressed "lz")))
 (project-aspects)
 (project-classes)
 (project-transformed-classes)
 (project-boot-classpath-directories)
 (project-boot-classpath-jar-files)
)