package jana.util.exceptions;

public class JAnalysisException extends Exception
{
	/**
	 * Generated by Eclipse
	 */
	private static final long serialVersionUID = -6724510637495918230L;

	public JAnalysisException(String string)
	{
		super(string);
	}

	public JAnalysisException(String aString, Exception anException)
	{
		super(aString, anException);
	}
}
