package jana.util.exceptions;

public class JElementNotFoundException extends Exception 
{
	/**
	 * generated by Eclipse
	 */
	private static final long serialVersionUID = 3093038035845029525L;

	public JElementNotFoundException(String anErrorMessage)
	{
		super(anErrorMessage);
	}
}
