package jana.util.exceptions;

import java.io.IOException;

public class JOutOfFilesException extends IOException
{
	/**
	 * Generated by Eclipse
	 */
	private static final long serialVersionUID = 4782522753083620392L;
	
	public JOutOfFilesException()
	{
	}

	public JOutOfFilesException(String message)
	{
		super(message);
	}

	public JOutOfFilesException(Throwable cause)
	{
		super(cause);
	}

	public JOutOfFilesException(String message, Throwable cause)
	{
		super(message, cause);
	}

}
