package jana.util.exceptions;

import java.io.IOException;

public class JParseException extends IOException
{

	/**
	 * Generated by Eclipse
	 */
	private static final long serialVersionUID = -9132611678535264473L;

	public JParseException(String anErrorMessage)
	{
		super(anErrorMessage);
	}
}
